In [39]:
import pandas as pd

In [40]:
df = pd.read_csv("tmdb-movies.csv")

In [41]:
df.columns

Index(['id', 'imdb_id', 'popularity', 'budget', 'revenue', 'original_title',
       'cast', 'homepage', 'director', 'tagline', 'keywords', 'overview',
       'runtime', 'genres', 'production_companies', 'release_date',
       'vote_count', 'vote_average', 'release_year', 'budget_adj',
       'revenue_adj'],
      dtype='object')

In [42]:
df_2006 = df[df['release_year']==2006]

In [43]:
df_2006.isnull()

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
6554,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6555,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6556,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6557,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6558,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6957,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
6958,False,False,False,False,False,False,False,True,False,True,...,False,False,False,True,False,False,False,False,False,False
6959,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
6960,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
6961,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [44]:
df_2006.dropna(axis=0,how = 'any')

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
6554,834,tt0401855,5.838503,50000000,111340801,Underworld: Evolution,Kate Beckinsale|Scott Speedman|Tony Curran|Sha...,http://www.sonypictures.com/movies/underworlda...,Len Wiseman,"My God. Brother, what have you done?",...,As the war between the vampires and the Lycans...,106,Fantasy|Action|Science Fiction|Thriller,Lakeshore Entertainment|Screen Gems,01-12-2006,1015,6.3,2006,5.408346e+07,1.204339e+08
6555,58,tt0383574,4.205992,200000000,1065659812,Pirates of the Caribbean: Dead Man's Chest,Johnny Depp|Orlando Bloom|Keira Knightley|Bill...,http://disney.go.com/disneypictures/pirates/,Gore Verbinski,Jack is back!,...,The high-seas adventures of happy-go-lucky tro...,151,Adventure|Fantasy|Action,Walt Disney Pictures|Jerry Bruckheimer Films|S...,6/20/06,3181,6.8,2006,2.163338e+08,1.152691e+09
6556,920,tt0317219,3.941265,120000000,461983149,Cars,Owen Wilson|Paul Newman|Bonnie Hunt|Larry the ...,http://disney.go.com/disneyvideos/animatedfilm...,John Lasseter|Joe Ranft,Ahhh... it's got that new movie smell.,...,"Lightning McQueen, a hotshot rookie race car d...",117,Animation|Adventure|Comedy|Family,Walt Disney Pictures|Pixar Animation Studios,06-08-2006,2336,6.4,2006,1.298003e+08,4.997129e+08
6557,36557,tt0381061,3.789580,150000000,599045960,Casino Royale,Daniel Craig|Eva Green|Mads Mikkelsen|Judi Den...,http://www.mgm.com/#/our-titles/233/Casino-Roy...,Martin Campbell,Everyone has a past. Every legend has a beginn...,...,"Le Chiffre, a banker to the world's terrorists...",144,Adventure|Action|Thriller,Eon Productions,11/14/06,2738,7.1,2006,1.622504e+08,6.479695e+08
6558,591,tt0382625,3.655536,125000000,758239851,The Da Vinci Code,Tom Hanks|Audrey Tautou|Ian McKellen|Paul Bett...,http://www.sonypictures.com/homevideo/thedavin...,Ron Howard,So Dark The Con Of Man,...,When the curator of the Louvre is found murder...,149,Thriller|Mystery,Columbia Pictures|Imagine Entertainment|Skylar...,5/17/06,1585,6.4,2006,1.352086e+08,8.201647e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6869,17,tt0411267,0.546134,0,0,The Dark,Sean Bean|Maria Bello|Richard Elfyn|Maurice Ro...,http://www.whatisannwyn.co.uk/,John Fawcett,One of the living for one of the dead.,...,AdÃ¨le and her daughter Sarah are traveling on...,87,Horror|Thriller|Mystery,Constantin Film|Impact Pictures|Isle of Man Fi...,1/26/06,31,5.2,2006,0.000000e+00,0.000000e+00
6881,7872,tt0468094,0.066302,0,0,The Road to Guantanamo,Riz Ahmed|Farhad Harun|Waqar Siddiqui|Afran Us...,http://www.roadtoguantanamomovie.com/,Mat Whitecross|Michael Winterbottom,How far will we go in the name of security?,...,"Part drama, part documentary, The Road to Guan...",95,Documentary|Drama,Screen West Midlands,03-09-2006,13,6.3,2006,0.000000e+00,0.000000e+00
6896,13751,tt0437800,0.133041,8000000,18948425,Akeelah and the Bee,Keke Palmer|Laurence Fishburne|Angela Bassett|...,http://www.akeelahandthebee.com/splash.html,Doug Atchison,Changing the world... one word at a time.,...,Eleven year-old Akeelah Anderson's life is not...,112,Drama,Lions Gate Films|2929 Productions|Out of the B...,4/28/06,46,6.6,2006,8.653353e+06,2.049593e+07
6908,7839,tt0484877,0.111308,0,0,Wedding Daze,Jason Biggs|Isla Fisher|Joe Pantoliano|Joanna ...,http://www.weddingdazemoviedvd.com/,Michael Ian Black,Marrying a complete stranger is a life sentence.,...,"After losing the woman of his dreams, Anderson...",90,Comedy|Romance,Warner Bros. Pictures|Fugitive Films|GreeneStr...,09-09-2006,50,5.6,2006,0.000000e+00,0.000000e+00
6927,14137,tt0453453,0.077689,0,0,Beer League,Artie Lange|Ralph Macchio|Anthony DeSando|Jimm...,http://www.beerleaguethemovie.com/,Frank Sebastiano,No Gut... No Glory.,...,An unemployed slacker (Lange) inspires his sof...,86,Comedy,Identity Films|CKRush Entertainment,9/15/06,12,4.9,2006,0.000000e+00,0.000000e+00

In [45]:
df_2006_runtime = df_2006['runtime']

In [46]:
df_2006_runtime

6554    106
6555    151
6556    117
6557    144
6558    149
       ...
6957    107
6958    100
6959     98
6960     92
6961    135
Name: runtime, Length: 408, dtype: int64

In [17]:
df_2006_runtime.describe()

count    408.000000
mean     101.683824
std       33.605027
min        0.000000
25%       90.000000
50%       98.000000
75%      110.000000
max      550.000000
Name: runtime, dtype: float64

In [18]:
sorted_df = df_2006_runtime.sort_values()

In [19]:
sorted_df

6934      0
6930      3
6736      5
6712      7
6760      7
       ...
6841    172
6827    185
6941    202
6829    270
6894    550
Name: runtime, Length: 408, dtype: int64

In [20]:
import numpy as np

In [21]:
q1,q3 = np.percentile(sorted_df,[25,75])

In [22]:
q1,q3

(90.0, 110.0)

In [23]:
iqr = q3-q1
iqr

20.0

In [24]:
lower_bound = q1 - (1.5*iqr)
upper_bound = q3 + (1.5*iqr)
lower_bound,upper_bound

(60.0, 140.0)

In [25]:
sorted_df[(sorted_df>lower_bound)&(sorted_df<upper_bound)]

6935     63
6651     69
6828     71
6688     72
6766     72
       ...
6961    135
6564    136
6704    136
6599    139
6681    139
Name: runtime, Length: 373, dtype: int64

In [26]:
sum = sorted_df.sum()
sum

41487

In [27]:
number_of_rows = sorted_df.shape
number_of_rows

(408,)

In [28]:
average = sum / number_of_rows

In [29]:
average

array([101.68382353])